name: 🐛 Bug Report
description: File a bug report here
title: ""
labels: ["type: bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: new-bug
    attributes:
      label: Is there an existing issue for this?
      description: Please search under [Issues](https://github.com/College-Kings/College-Kings-2/issues) to see if an issue already exists for the bug you are about to report.
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    id: scene-id
    attributes:
      label: Scene number
      description: We need a scene and/or image ID
      placeholder: v3s30, v2s24_15c etc.
    validations:
      required: true
  - type: textarea
    id: bug-desription
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      # placeholder: 
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
      # placeholder: 
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: Windows 10
          - **Version**: 7.6.4
      value: |
        - OS:
        - Version:
      render: Markdown
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      # placeholder: 
    validations:
      required: false
  - type: dropdown
    id: versions
    attributes:
      label: Which version of the app are you using?
      description: If this issue is occurring on more than 1 version of the app, select the appropriate versions.
      multiple: true
      options:
        - 1.0.0
        - 1.1.0
        - 1.2.0
        - 2.0.0
        - 2.1.0
    validations:
      required: true