name: 🐛 Bug Report
description: File a bug report here
title: []
labels: ["type: bug"]
assignees:
  - space-storm
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: checkboxes
    id: new-bug
    attributes:
      label: Is there an existing issue for this?
      description: Please search under [Issues](https://github.com/College-Kings/College-Kings-2/issues) to see if an issue already exists for the bug you are about to report.
      options:
        - label: I have searched the existing issues
          required: true

  - type: input
    id: scene-id
    attributes:
      label: Scene number
      description: We need a scene and/or image ID
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: |
        What priority would you consider this issue to be?
        P4 - Lowest, P1 - Highest
      multiple: false
      options:
        - P4
        - P3
        - P2
        - P1
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      # placeholder: 
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      # placeholder: 
    validations:
      required: false

  - type: textarea
    id: additional-info
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      # placeholder: 
    validations:
      required: false

  - type: dropdown
    id: environment
    attributes:
      label: What is the OS version you are playing on?
      description: If you select "Other", please provide the OS name and version in the box below.
      multiple: false
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
